### ISSUE TITLE
SurfaceDuoLayout and startActivity

### ISSUE THREAD

**Issue by letisoft** [microsoft/surface-duo-sdk#8] opened 2021-01-20 08:03 UTC
Hello,

I have very simple app - on activity with only a SurfaceDuoLayout as simple as this:

    <com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:single_screen_layout_id="@layout/view_single"
        app:dual_screen_start_layout_id="@layout/view_left"
        app:dual_screen_end_layout_id="@layout/view_right"
        app:tools_screen_mode="dual_screen">

It all works when I start the app:
app starts in single screen, drag it to the hinge and it becomes dual screen all works fine.
Now if create the same activity by startActivity it always starts as single mode (and I can even not drag it again), app is in duo mode so as a result I got same activity spanned as it displays the single view

onScreenInfoChanged seems correct (getting single/duo as expected) but the following code inside SurfaceDuoLayout gets confused:

setupViewModel method viewModel is single for the second start?

Any idea what's wrong?

**Comment by ancirja-m** [comment] 2021-01-20 11:09
Hi @letisoft,

Thanks for your detailed message. We are aware of this issue and we are currently working on it. The fix will be provided with the next alpha version (will be published asap).

Please, let us know with any other issue you may have,

Thanks,
Andrei

**Comment by letisoft** [comment] 2021-01-20 11:13
Hello,

Thank you very much for the quick response, but how can I get my app working?

All I need is start activity in spanned mode while the app is already in spanned mode?

I have activity A and once a button is clicked I need it to start activity B but in dual screen as activity A is in dual screen already?

What is the way to achieve this?

Thanks again!

**Comment by letisoft** [comment] 2021-01-21 09:06
Hello,

Sorry for pushing, but it is good to know if there is a way to bypass the issue, right now it looks like this is a showstopper and I hope there is a way to move forward.

Thank you very much!

**Comment by ancirja-m** [comment] 2021-01-21 10:42
Hey @letisoft,
 
We currently have a bug that prevents you to launch a new Activity using the SurfaceDuoLayout when the app is spanned and keeping that state.
The fix is almost finished, and will be included in the next release.
 
In the meantime, what you can do is instead of launching a new Activity is to replace your Activities for fragments, so you just replace fragments while keeping just one Activity.
We understand that this scenario is maybe a no-go for you, if this is the case, please, wait till we have the new version released that will fix the problem.
 
Thanks,
Andrei

**Comment by letisoft** [comment] 2021-01-21 12:12
Thank you for the update. When is next release due?

**Comment by ancirja-m** [comment] 2021-01-21 15:03
Hi @letisoft ,

We cannot provide a specific ETA, but it should not take long (we would like to have it next month).

Thanks,
Andrei

**Closed** 2021-02-17 15:15 UTC
Labels: bug

**Comment by letisoft** [comment] 2021-03-16 16:18
Hello,

Any update on this one?
I am not that good with git hub - will I get update once bug is fixed?

Thanks

**Comment by CesarValiente** [comment] 2021-03-16 16:21
Hey,

fix was already merged and avaialable in `beta2` version of the library available in JCenter. 
See the PR: https://github.com/microsoft/surface-duo-sdk/pull/10 for more info and the release tag: https://github.com/microsoft/surface-duo-sdk/releases/tag/02172021

Thanks,
Cesar

**Comment by letisoft** [comment] 2021-03-17 07:45
Hello,

Strange I have only changed

    implementation "com.microsoft.device.dualscreen:layouts:1.0.0-beta1"
    implementation "com.microsoft.device.dualscreen:screenmanager-windowmanager:1.0.0-beta1"
to
    implementation "com.microsoft.device.dualscreen:layouts:1.0.0-beta2"
    implementation "com.microsoft.device.dualscreen:screenmanager-windowmanager:1.0.0-beta2"


And now app crashes:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{info.tinyapps.duotest/info.tinyapps.duotest.MainActivity}: android.view.InflateException: Binary XML file line #21 in info.tinyapps.duotest:layout/activity_main: Binary XML file line #21 in info.tinyapps.duotest:layout/activity_main: Error inflating class com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3275)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3414)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7367)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
     Caused by: android.view.InflateException: Binary XML file line #21 in info.tinyapps.duotest:layout/activity_main: Binary XML file line #21 in info.tinyapps.duotest:layout/activity_main: Error inflating class com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout
     Caused by: android.view.InflateException: Binary XML file line #21 in info.tinyapps.duotest:layout/activity_main: Error inflating class com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at info.tinyapps.duotest.MainActivity.onCreate(MainActivity.java:19)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3414)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2021)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7367)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
     Caused by: java.lang.IllegalStateException: property javaClass (Kotlin reflection is not available) must be initialized inside Application#onCreate()
2021-03-17 09:45:00.159 5971-5971/info.tinyapps.duotest E/AndroidRuntime:     at com.microsoft.device.dualscreen.ScreenManagerProvider.getScreenManager(ScreenManagerProvider.kt:32)
        at com.microsoft.device.dualscreen.layouts.ScreenSavedState.<init>(ScreenSavedState.kt:22)
        at com.microsoft.device.dualscreen.layouts.SurfaceDuoLayoutViewModel.<init>(SurfaceDuoLayoutViewModel.kt:17)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout.setupViewModel(SurfaceDuoLayout.kt:81)
        at com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout.<init>(SurfaceDuoLayout.kt:73)
        at com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout.<init>(SurfaceDuoLayout.kt:42)
        at com.microsoft.device.dualscreen.layouts.SurfaceDuoLayout.<init>(Unknown Source:8)
        	... 28 more

Please note no other changes at all?

Thank you!

**Comment by CesarValiente** [comment] 2021-03-17 10:42
We think you have missed the configuration step for the ScreenManager where you need to set it up: https://docs.microsoft.com/dual-screen/android/api-reference/dualscreen-library/core/surfaceduo-screen-manager?tabs=kotlin

Specifically this code snippet:

```
class SampleApp : Application() {
    override fun onCreate() {
        super.onCreate()
        ScreenManagerProvider.init(this)
    }
}
```
Where you need to create an `Application` class that extends from Application and initialize `ScreenManager` before being able to use it.
You also have sample apps inside this code repo that can help you to understand how to use the components.

Thanks,
Cesar

**Comment by letisoft** [comment] 2021-03-17 10:55
Thank you very much!

Yes this was the problem and it was OK with the old version of the libs

Thank you again!

**Comment by CesarValiente** [comment] 2021-03-17 11:34
Awesome!! Glad to hear that the problem is fixed.

Oh FYI, feel free to keep opening issues as you find problems (thanks a lot for doing that!), and if you have any other question, ideas, proposals, complains, etc. feel free to use our discussions channel that we have just set it up: https://github.com/microsoft/surface-duo-sdk/discussions

Thanks,
Cesar
